const quotes = [
    "Believe you can and you're halfway there.",
    "In the middle of difficulty lies opportunity.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only way to do great work is to love what you do.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "The only thing we have to fear is fear itself.",
    "It is never too late to be what you might have been.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Happiness is not something ready-made. It comes from your own actions.",
    "You miss 100% of the shots you don't take.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Life is what happens when you're busy making other plans.",
    "The greatest wealth is to live content with little.",
    "The only true wisdom is in knowing you know nothing.",
    "We may encounter many defeats but we must not be defeated.",
    "It always seems impossible until it's done.",
    "Life is either a daring adventure or nothing at all.",
    "The best revenge is massive success.",
    "If you want to lift yourself up, lift up someone else.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "If you're going through hell, keep going.",
    "The purpose of our lives is to be happy.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "You must be the change you wish to see in the world.",
    "I am not a product of my circumstances. I am a product of my decisions.",
    "The only way to predict the future is to create it.",
    "Opportunities don't happen, you create them.",
    "It's not what you look at that matters, it's what you see.",
    "The only person you should try to be better than is the person you were yesterday.",
    "You can never cross the ocean until you have the courage to lose sight of the shore.",
    "Don't watch the clock; do what it does. Keep going.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "I have not failed. I've just found 10,000 ways that won't work.",
    "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
    "The journey of a thousand miles begins with one step.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "Whether you think you can or you think you can't, you're right.",
    "The greatest pleasure in life is doing what people say you cannot do.",
    "I am thankful for all of those who said NO to me. It's because of them I'm doing it myself.",
    "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
    "It is during our darkest moments that we must focus to see the light.",
    "The only person who is educated is the one who has learned how to learn...and change.",
    "The greatest danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it.",
    "You never know what you can do until you try.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Life is like riding a bicycle. To keep your balance, you must keep moving."
];

function newQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    const randomQuote = quotes[randomIndex];
    document.getElementById("quoteDisplay").innerHTML = randomQuote;
}